### ISSUE TITLE
Age group required

### ISSUE THREAD

**Issue by camnewnham** [RageAgainstThePixel/upload-meta-quest-build#10]
Meta has introduced a policy where specifying the age group is required.

> Required. (If not specified, the upload will go into “draft” status, rather than failing.) Age group of the build. This can be TEENS_AND_ADULTS, MIXED_AGES, or CHILDREN.

This just needs to be included in the build command as `--age-group` i.e. `--age-group TEENS_AND_ADULTS`.
See https://developer.oculus.com/resources/publish-reference-platform-command-line-utility/#upload-quest

**Comment by StephenHodgson** [comment]
Sounds good!
