### ISSUE TITLE
Docs are missing optional parameters

### ISSUE THREAD

**Issue by sm-quasar** [RageAgainstThePixel/upload-meta-quest-build#3]
Hello, 

Your docs are missing the optional params also offered by this action

I've tried to write them out as best I could from the source code

If I could get write access I'm happy to raise a PR

Otherwise, here's what I've got so far

### All Params
| Name | Description | Default | Optional
| ---- | ----------- | ------- |---------|
| appId | Your App ID from the meta store | "" | No |
| appSecret | Your App secret from the meta store | "" | Must provide appSecret or token |
| token | The App ID from the meta store | "" | Must provide appSecret or token |
| apkPath | Path to the APK to upload | "" | No |
| obbPath | Path to an obb file to upload | "" | Yes |
| assetsDir | DLC Content to upload | "" | Yes |
| releaseChannel | Which release channel to upload the apk to | "ALPHA" | Yes |
| releaseNotes | Release notes to upload | "" | Yes |
| assetFilesConfig | DLC Config | "" | Yes |
| languagePacksDir | Additional languages | "" | Yes |
| debugSymbolsDir | Path to the folder that contains the debug symbol file(s) | "" | Yes |
| debugSymbolsPattern | Specifies a file pattern that matches the filesnames of all debug symbol files | "" | Yes |

**Comment by StephenHodgson** [comment]
I'm not entirely sure I added support for all these, but you're more than welcome to add to the documentation

**Comment by sm-quasar** [comment]
The options for reading each of these params in and passing to the uploader exe looks to be correct as best I can tell anyway

**Comment by sm-quasar** [comment]
If you can grant me write access (even temporarily I'll pop the PR up to date the docs, changes are all sat waiting locally just can't push :D

**Comment by StephenHodgson** [comment]
I see you've already created a fork. It should be no problem to open a PR with it.

**Comment by sm-quasar** [comment]
That should be done now

I initially forked it this morning more by accident so it might look like a new fork now
